#!/bin/bash

# Usage:
#  $1 Trac URL
#  $2 Path to Trac installation

set -e

URL="$1"
tracpath="$2"

CMD="$(dirname $(readlink -f $0))/trac-post-commit-hook"
GITREVCMD="$(dirname $(readlink -f $0))/git-find-revs"
FILE="`mktemp -t git-trac-commit.XXXXXXXXXX`"

procrevs() {
    while read gitrev; do
        git show -s --pretty "$gitrev" > "$FILE"
        "$CMD" -p "$tracpath" -r "$gitrev" \
            -u "`git show -s --pretty=format:%an ${gitrev}`" \
            -s "$URL" \
            -m "`git show -s --pretty=format:%s%n%b ${gitrev}`"
    done
}

${GITREVCMD} | procrevs

rm "$FILE"

exit 0